### ISSUE TITLE
Application overview visible below search results and window overview

### ISSUE THREAD

**Issue by Nevon** [lassekongo83/zuki-themes#40] opened 2015-04-26 08:05 UTC
Apologies for the title, I'm not sure what to call the various elements.

I'm using the latest versions of Zukitwo and ZukiShell in Gnome 3.14.4. When I open the activities overview, the applications open in this workspace are displayed on top of the frequently used applications list:

![Applications view](http://i.imgur.com/LODuCIM.jpg)

The same thing happens if I search for something:

![Searching](http://i.imgur.com/dVD3bh4.jpg)

**Comment by lassekongo83** [comment] 2016-04-02 17:45
Sorry for the very late reply. Couldn't reproduce this when I used 3.14. Seems like a graphics driver issue or Gnome configuration issue. Issue is probably outdated and unrelated to the theme. Closing it.

**Closed by lassekongo83** 2016-04-02 17:45 UTC
